FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install @babylonjs/core
RUN npm install @babylonjs/gui

COPY . .


# Ouvre le port pour vite
EXPOSE 5173

RUN npm run build:css

CMD ["npm", "run", "dev"]