FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install @babylonjs/core
RUN npm install @babylonjs/gui
RUN npm install @babylonjs/loaders

COPY public ./public
COPY src ./src
COPY vite.config.ts ./
COPY index.html ./


COPY . .
RUN chmod +x entrypoint.sh

RUN npm run build:css
# RUN npm run build # Uncomment if you want to build the project for production

ENTRYPOINT ["bash", "entrypoint.sh"]
