# Stage 1: Build frontend with Vite
FROM node:20-slim AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
# Force install specific Babylon.js dependencies
RUN npm install @babylonjs/core @babylonjs/addons --save
COPY . .
RUN npm run build

# Stage 2: Build final container with Nginx-full + ModSecurity
FROM debian:bookworm-slim

# Install Nginx with ModSecurity
RUN apt-get update && apt-get install -y \
    nginx-full \
    libmodsecurity3 \
    libnginx-mod-http-modsecurity \
    git \
    curl && \
    rm -rf /var/lib/apt/lists/*

# Copy custom Nginx config
COPY ./nginx_conf/nginx.dev.conf /etc/nginx/nginx.conf

# Copy ModSecurity configuration as entrypoint
COPY ./nginx_conf/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# COPY ./nginx_conf/certs/generate.sh /generate_certs.sh
# RUN chmod +x /generate_certs.sh
# RUN generate_certs.sh

# COPY ./nginx_conf/certs/server.crt /etc/nginx/certs/server.crt
# COPY ./nginx_conf/certs/server.key /etc/nginx/certs/server.key

COPY ./nginx_conf/certs/ssl.conf /etc/nginx/certs/ssl.conf
COPY ./nginx_conf/certs/CA/CA.ext /etc/nginx/certs/CA/CA.ext

# Copy frontend build from previous stage
COPY --from=builder /app/dist /var/www/html

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
