version: '3.8'

services:
  backend:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  logstash:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  filebeat:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  elasticsearch:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  kibana:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
