version: '3'
services:
  backend-node:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  backend-php:
    image: php:8.0-apache
    volumes:
      - ./php-app:/var/www/html
    ports:
      - "8080:80"