
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/data
  
    environment:
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - ft_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - ft_network
    expose:
      - "80"

  db:
    image: mongo:latest
    volumes:
      - db-data:/app/data
    networks:
      - ft_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ft_network

volumes:
  db-data:

networks:
  ft_network:
