FROM grafana/grafana:latest

USER root

RUN apk update && \
	apk upgrade && \
	apk add --no-cache jq

COPY ./config/entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh

USER grafana

ENTRYPOINT ["/bin/entrypoint.sh"]
