FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install && apt-get update && apt-get install sqlite3 -y

COPY . .

# COPY ../../../../prisma/ ./prisma

RUN chmod +x ./config/start.sh

CMD ["/bin/sh", "./config/start.sh"]

