# Étape de dev pour le backend
FROM node:20-slim

RUN apt-get update && apt-get install -y \
	git \
	zsh \
	net-tools \
	bash

# Creer le fichier de configuration pour sqlite
# RUN mkdir -p /var/lib/sqlite
# RUN touch /var/lib/sqlite/db.sqlite

# Copie les fichiers package.json + lock
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste du code
COPY . .

RUN chmod +x ./config/start.sh
COPY ./src/utils/easter-egg.sh /app/easter-egg.sh
RUN chmod +x /app/easter-egg.sh
RUN npx prisma generate

# Commande de dev
ENTRYPOINT ["/bin/sh", "./config/start.sh"]
